import { Team } from '../../models/individual/team/team';

export let nbaTeams: Team[] = [
    new Team({
        fullName: 'Atlanta Hawks',
        regionFullName: 'Atlanta',
        regionAbbreviation: 'ATL',
        teamFullName: 'Hawks',
        teamAbbreviation: 'Hawks',
        altNames: [],
    }),
    new Team({
        fullName: 'Boston Celtics',
        regionFullName: 'Boston',
        regionAbbreviation: 'BOS',
        teamFullName: 'Celtics',
        teamAbbreviation: 'Celtics',
        altNames: [],
    }),
    new Team({
        fullName: 'Brooklyn Nets',
        regionFullName: 'Brooklyn',
        regionAbbreviation: 'BKN',
        teamFullName: 'Nets',
        teamAbbreviation: 'Nets',
        altNames: [],
    }),
    new Team({
        fullName: 'Charlotte Hornets',
        regionFullName: 'Charlotte',
        regionAbbreviation: 'CHA',
        teamFullName: 'Hornets',
        teamAbbreviation: 'Hornets',
        altNames: [],
    }),
    new Team({
        fullName: 'Chicago Bulls',
        regionFullName: 'Chicago',
        regionAbbreviation: 'CHI',
        teamFullName: 'Bulls',
        teamAbbreviation: 'Bulls',
        altNames: [],
    }),
    new Team({
        fullName: 'Cleveland Cavaliers',
        regionFullName: 'Cleveland',
        regionAbbreviation: 'CLE',
        teamFullName: 'Cavaliers',
        teamAbbreviation: 'Cavs',
        altNames: [],
    }),
    new Team({
        fullName: 'Dallas Mavericks',
        regionFullName: 'Dallas',
        regionAbbreviation: 'DAL',
        teamFullName: 'Mavericks',
        teamAbbreviation: 'Mavs',
        altNames: [],
    }),
    new Team({
        fullName: 'Denver Nuggets',
        regionFullName: 'Denver',
        regionAbbreviation: 'DEN',
        teamFullName: 'Nuggets',
        teamAbbreviation: 'Nugs',
        altNames: [],
    }),
    new Team({
        fullName: 'Detroit Pistons',
        regionFullName: 'Detroit',
        regionAbbreviation: 'DET',
        teamFullName: 'Pistons',
        teamAbbreviation: 'Pistons',
        altNames: [],
    }),
    new Team({
        fullName: 'Golden State Warriors',
        regionFullName: 'Golden State',
        regionAbbreviation: 'GSW',
        teamFullName: 'Warriors',
        teamAbbreviation: 'Warriors',
        altNames: [],
    }),
    new Team({
        fullName: 'Houston Rockets',
        regionFullName: 'Houston',
        regionAbbreviation: 'HOU',
        teamFullName: 'Rockets',
        teamAbbreviation: 'Rockets',
        altNames: [],
    }),
    new Team({
        fullName: 'Indiana Pacers',
        regionFullName: 'Indiana',
        regionAbbreviation: 'IND',
        teamFullName: 'Pacers',
        teamAbbreviation: 'Pacers',
        altNames: [],
    }),
    new Team({
        fullName: 'Los Angeles Clippers',
        regionFullName: 'Los Angeles',
        regionAbbreviation: 'LAC',
        teamFullName: 'Clippers',
        teamAbbreviation: 'Clippers',
        altNames: [],
    }),
    new Team({
        fullName: 'Los Angeles Lakers',
        regionFullName: 'Los Angeles',
        regionAbbreviation: 'LAL',
        teamFullName: 'Lakers',
        teamAbbreviation: 'Lakers',
        altNames: [],
    }),
    new Team({
        fullName: 'Memphis Grizzlies',
        regionFullName: 'Memphis',
        regionAbbreviation: 'MEM',
        teamFullName: 'Grizzlies',
        teamAbbreviation: 'Grizzlies',
        altNames: [],
    }),
    new Team({
        fullName: 'Miami Heat',
        regionFullName: 'Miami',
        regionAbbreviation: 'MIA',
        teamFullName: 'Heat',
        teamAbbreviation: 'Heat',
        altNames: [],
    }),
    new Team({
        fullName: 'Milwaukee Bucks',
        regionFullName: 'Milwaukee',
        regionAbbreviation: 'MIL',
        teamFullName: 'Bucks',
        teamAbbreviation: 'Bucks',
        altNames: [],
    }),
    new Team({
        fullName: 'Minnesota Timberwolves',
        regionFullName: 'Minnesota',
        regionAbbreviation: 'MIN',
        teamFullName: 'Timberwolves',
        teamAbbreviation: 'Wolves',
        altNames: [],
    }),
    new Team({
        fullName: 'New Orleans Pelicans',
        regionFullName: 'New Orleans',
        regionAbbreviation: 'NOP',
        teamFullName: 'Pelicans',
        teamAbbreviation: 'Pels',
        altNames: [],
    }),
    new Team({
        fullName: 'New York Knicks',
        regionFullName: 'New York',
        regionAbbreviation: 'NYK',
        teamFullName: 'Knicks',
        teamAbbreviation: 'Knicks',
        altNames: [],
    }),
    new Team({
        fullName: 'Oklahoma City Thunder',
        regionFullName: 'Oklahoma City',
        regionAbbreviation: 'OKC',
        teamFullName: 'Thunder',
        teamAbbreviation: 'Thunder',
        altNames: [],
    }),
    new Team({
        fullName: 'Orlando Magic',
        regionFullName: 'Orlando',
        regionAbbreviation: 'ORL',
        teamFullName: 'Magic',
        teamAbbreviation: 'Magic',
        altNames: [],
    }),
    new Team({
        fullName: 'Philadelphia 76ers',
        regionFullName: 'Philadelphia',
        regionAbbreviation: 'PHI',
        teamFullName: '76ers',
        teamAbbreviation: 'Sixers',
        altNames: [],
    }),
    new Team({
        fullName: 'Phoenix Suns',
        regionFullName: 'Phoenix',
        regionAbbreviation: 'PHX',
        teamFullName: 'Suns',
        teamAbbreviation: 'Suns',
        altNames: [],
    }),
    new Team({
        fullName: 'Portland Trail Blazers',
        regionFullName: 'Portland',
        regionAbbreviation: 'POR',
        teamFullName: 'Trail Blazers',
        teamAbbreviation: 'Blazers',
        altNames: [],
    }),
    new Team({
        fullName: 'Sacramento Kings',
        regionFullName: 'Sacramento',
        regionAbbreviation: 'SAC',
        teamFullName: 'Kings',
        teamAbbreviation: 'Kings',
        altNames: [],
    }),
    new Team({
        fullName: 'San Antonio Spurs',
        regionFullName: 'San Antonio',
        regionAbbreviation: 'SAS',
        teamFullName: 'Spurs',
        teamAbbreviation: 'Spurs',
        altNames: [],
    }),
    new Team({
        fullName: 'Toronto Raptors',
        regionFullName: 'Toronto',
        regionAbbreviation: 'TOR',
        teamFullName: 'Raptors',
        teamAbbreviation: 'Raptors',
        altNames: [],
    }),
    new Team({
        fullName: 'Utah Jazz',
        regionFullName: 'Utah',
        regionAbbreviation: 'UTA',
        teamFullName: 'Jazz',
        teamAbbreviation: 'Jazz',
        altNames: [],
    }),
    new Team({
        fullName: 'Washington Wizards',
        regionFullName: 'Washington',
        regionAbbreviation: 'WAS',
        teamFullName: 'Wizards',
        teamAbbreviation: 'Wizards',
        altNames: [],
    })
];
       

