import { Team } from '../../models/individual/team/team';

export let nflTeams: Team[] = [
    new Team({
        fullName: 'Arizona Cardinals',
        regionFullName: 'Arizona',
        regionAbbreviation: 'ARI',
        teamFullName: 'Cardinals',
        teamAbbreviation: 'Cards',
        altNames: [],
    }),
    new Team({
        fullName: 'Atlanta Falcons',
        regionFullName: 'Atlanta',
        regionAbbreviation: 'ATL',
        teamFullName: 'Falcons',
        teamAbbreviation: 'Falcs',
        altNames: [],
    }),
    new Team({
        fullName: 'Baltimore Ravens',
        regionFullName: 'Baltimore',
        regionAbbreviation: 'BAL',
        teamFullName: 'Ravens',
        teamAbbreviation: 'Raves',
        altNames: [],
    }),
    new Team({
        fullName: 'Buffalo Bills',
        regionFullName: 'Buffalo',
        regionAbbreviation: 'BUF',
        teamFullName: 'Bills',
        teamAbbreviation: 'Bills',
        altNames: [],
    }),
    new Team({
        fullName: 'Carolina Panthers',
        regionFullName: 'Carolina',
        regionAbbreviation: 'CAR',
        teamFullName: 'Panthers',
        teamAbbreviation: 'Pants',
        altNames: [],
    }),
    new Team({
        fullName: 'Chicago Bears',
        regionFullName: 'Chicago',
        regionAbbreviation: 'CHI',
        teamFullName: 'Bears',
        teamAbbreviation: 'Bears',
        altNames: [],
    }),
    new Team({
        fullName: 'Cincinnati Bengals',
        regionFullName: 'Cincinnati',
        regionAbbreviation: 'CIN',
        teamFullName: 'Bengals',
        teamAbbreviation: 'Bengs',
        altNames: [],
    }),
    new Team({
        fullName: 'Cleveland Browns',
        regionFullName: 'Cleveland',
        regionAbbreviation: 'CLE',
        teamFullName: 'Browns',
        teamAbbreviation: 'Browns',
        altNames: [],
    }),
    new Team({
        fullName: 'Dallas Cowboys',
        regionFullName: 'Dallas',
        regionAbbreviation: 'DAL',
        teamFullName: 'Cowboys',
        teamAbbreviation: 'Boys',
        altNames: [],
    }),
    new Team({
        fullName: 'Denver Broncos',
        regionFullName: 'Denver',
        regionAbbreviation: 'DEN',
        teamFullName: 'Broncos',
        teamAbbreviation: 'Broncs',
        altNames: [],
    }),
    new Team({
        fullName: 'Detroit Lions',
        regionFullName: 'Detroit',
        regionAbbreviation: 'DET',
        teamFullName: 'Lions',
        teamAbbreviation: 'Lions',
        altNames: [],
    }),
    new Team({
        fullName: 'Green Bay Packers',
        regionFullName: 'Green Bay',
        regionAbbreviation: 'GB',
        teamFullName: 'Packers',
        teamAbbreviation: 'Packs',
        altNames: [],
    }),
    new Team({
        fullName: 'Houston Texans',
        regionFullName: 'Houston',
        regionAbbreviation: 'HOU',
        teamFullName: 'Texans',
        teamAbbreviation: 'Texns',
        altNames: [],
    }),
    new Team({
        fullName: 'Indianapolis Colts',
        regionFullName: 'Indianapolis',
        regionAbbreviation: 'IND',
        teamFullName: 'Colts',
        teamAbbreviation: 'Colts',
        altNames: [],
    }),
    new Team({
        fullName: 'Jacksonville Jaguars',
        regionFullName: 'Jacksonville',
        regionAbbreviation: 'JAX',
        teamFullName: 'Jaguars',
        teamAbbreviation: 'Jags',
        altNames: [],
    }),
    new Team({
        fullName: 'Kansas City Chiefs',
        regionFullName: 'Kansas City',
        regionAbbreviation: 'KC',
        teamFullName: 'Chiefs',
        teamAbbreviation: 'Chiefs',
        altNames: [],
    }),
    new Team({
        fullName: 'Las Vegas Raiders',
        regionFullName: 'Las Vegas',
        regionAbbreviation: 'LAV',
        teamFullName: 'Raiders',
        teamAbbreviation: 'Raids',
        altNames: [],
    }),
    new Team({
        fullName: 'Los Angeles Chargers',
        regionFullName: 'Los Angeles',
        regionAbbreviation: 'LAC',
        teamFullName: 'Chargers',
        teamAbbreviation: 'Chargers',
        altNames: [],
    }),
    new Team({
        fullName: 'Los Angeles Rams',
        regionFullName: 'Los Angeles',
        regionAbbreviation: 'LAR',
        teamFullName: 'Rams',
        teamAbbreviation: 'Rams',
        altNames: [],
    }),
    new Team({
        fullName: 'Miami Dolphins',
        regionFullName: 'Miami',
        regionAbbreviation: 'MIA',
        teamFullName: 'Dolphins',
        teamAbbreviation: 'Fins',
        altNames: [],
    }),
    new Team({
        fullName: 'Minnesota Vikings',
        regionFullName: 'Minnesota',
        regionAbbreviation: 'MIN',
        teamFullName: 'Vikings',
        teamAbbreviation: 'Vikes',
        altNames: [],
    }),
    new Team({
        fullName: 'New England Patriots',
        regionFullName: 'New England',
        regionAbbreviation: 'NE',
        teamFullName: 'Patriots',
        teamAbbreviation: 'Pats',
        altNames: [],
    }),
    new Team({
        fullName: 'New Orleans Saints',
        regionFullName: 'New Orleans',
        regionAbbreviation: 'NO',
        teamFullName: 'Saints',
        teamAbbreviation: 'Saints',
        altNames: [],
    }),
    new Team({
        fullName: 'New York Giants',
        regionFullName: 'New York',
        regionAbbreviation: 'NYG',
        teamFullName: 'Giants',
        teamAbbreviation: 'G-Men',
        altNames: [],
    }),
    new Team({
        fullName: 'New York Jets',
        regionFullName: 'New York',
        regionAbbreviation: 'NYJ',
        teamFullName: 'Jets',
        teamAbbreviation: 'Jets',
        altNames: [],
    }),
    new Team({
        fullName: 'Philadelphia Eagles',
        regionFullName: 'Philadelphia',
        regionAbbreviation: 'PHI',
        teamFullName: 'Eagles',
        teamAbbreviation: 'Eags',
        altNames: [],
    }),
    new Team({
        fullName: 'Pittsburgh Steelers',
        regionFullName: 'Pittsburgh',
        regionAbbreviation: 'PIT',
        teamFullName: 'Steelers',
        teamAbbreviation: 'Steels',
        altNames: [],
    }),
    new Team({
        fullName: 'San Francisco 49ers',
        regionFullName: 'San Francisco',
        regionAbbreviation: 'SF',
        teamFullName: '49ers',
        teamAbbreviation: 'Niners',
        altNames: [],
    }),
    new Team({
        fullName: 'Seattle Seahawks',
        regionFullName: 'Seattle',
        regionAbbreviation: 'SEA',
        teamFullName: 'Seahawks',
        teamAbbreviation: 'Hawks',
        altNames: [],
    }),
    new Team({
        fullName: 'Tampa Bay Buccaneers',
        regionFullName: 'Tampa Bay',
        regionAbbreviation: 'TB',
        teamFullName: 'Buccaneers',
        teamAbbreviation: 'Bucs',
        altNames: [],
    }),
    new Team({
        fullName: 'Tennessee Titans',
        regionFullName: 'Tennessee',
        regionAbbreviation: 'TEN',
        teamFullName: 'Titans',
        teamAbbreviation: 'Titans',
        altNames: [],
    }),
    new Team({
        fullName: 'Washington Commanders',
        regionFullName: 'Washington',
        regionAbbreviation: 'WAS',
        teamFullName: 'Commanders',
        teamAbbreviation: 'Commanders',
        altNames: [],
    })
];