import { TeamInitData } from '.';

export const nflTeamsInitData = [
  new TeamInitData({
    regionFull: 'Arizona',
    regionAbbr: 'ARI',
    identifierFull: 'Cardinals',
    identifierAbbr: 'Cards',
  }),
  new TeamInitData({
    regionFull: 'Atlanta',
    regionAbbr: 'ATL',
    identifierFull: 'Falcons',
    identifierAbbr: 'Falcs',
  }),
  new TeamInitData({
    regionFull: 'Baltimore',
    regionAbbr: 'BAL',
    identifierFull: 'Ravens',
    identifierAbbr: 'Ravens',
  }),
  new TeamInitData({
    regionFull: 'Buffalo',
    regionAbbr: 'BUF',
    identifierFull: 'Bills',
    identifierAbbr: 'Bills',
  }),
  new TeamInitData({
    regionFull: 'Carolina',
    regionAbbr: 'CAR',
    identifierFull: 'Panthers',
    identifierAbbr: 'Panthers',
  }),
  new TeamInitData({
    regionFull: 'Chicago',
    regionAbbr: 'CHI',
    identifierFull: 'Bears',
    identifierAbbr: 'Bears',
  }),
  new TeamInitData({
    regionFull: 'Cincinnati',
    regionAbbr: 'CIN',
    identifierFull: 'Bengals',
    identifierAbbr: 'Bengals',
  }),
  new TeamInitData({
    regionFull: 'Cleveland',
    regionAbbr: 'CLE',
    identifierFull: 'Browns',
    identifierAbbr: 'Browns',
  }),
  new TeamInitData({
    regionFull: 'Dallas',
    regionAbbr: 'DAL',
    identifierFull: 'Cowboys',
    identifierAbbr: 'Cowboys',
  }),
  new TeamInitData({
    regionFull: 'Denver',
    regionAbbr: 'DEN',
    identifierFull: 'Broncos',
    identifierAbbr: 'Broncs',
  }),
  new TeamInitData({
    regionFull: 'Detroit',
    regionAbbr: 'DET',
    identifierFull: 'Lions',
    identifierAbbr: 'Lions',
  }),
  new TeamInitData({
    regionFull: 'Green Bay',
    regionAbbr: 'GB',
    identifierFull: 'Packers',
    identifierAbbr: 'Packers',
  }),
  new TeamInitData({
    regionFull: 'Houston',
    regionAbbr: 'HOU',
    identifierFull: 'Texans',
    identifierAbbr: 'Texans',
  }),
  new TeamInitData({
    regionFull: 'Indianapolis',
    regionAbbr: 'IND',
    identifierFull: 'Colts',
    identifierAbbr: 'Colts',
  }),
  new TeamInitData({
    regionFull: 'Jacksonville',
    regionAbbr: 'JAX',
    identifierFull: 'Jaguars',
    identifierAbbr: 'Jags',
  }),
  new TeamInitData({
    regionFull: 'Kansas City',
    regionAbbr: 'KC',
    identifierFull: 'Chiefs',
    identifierAbbr: 'Chiefs',
  }),
  new TeamInitData({
    regionFull: 'Las Vegas',
    regionAbbr: 'LV',
    identifierFull: 'Raiders',
    identifierAbbr: 'Raiders',
  }),
  new TeamInitData({
    regionFull: 'Los Angeles',
    regionAbbr: 'LAC',
    identifierFull: 'Chargers',
    identifierAbbr: 'Chargers',
  }),
  new TeamInitData({
    regionFull: 'Los Angeles',
    regionAbbr: 'LAR',
    identifierFull: 'Rams',
    identifierAbbr: 'Rams',
  }),
  new TeamInitData({
    regionFull: 'Miami',
    regionAbbr: 'MIA',
    identifierFull: 'Dolphins',
    identifierAbbr: 'Fins',
  }),
  new TeamInitData({
    regionFull: 'Minnesota',
    regionAbbr: 'MIN',
    identifierFull: 'Vikings',
    identifierAbbr: 'Vikes',
  }),
  new TeamInitData({
    regionFull: 'New England',
    regionAbbr: 'NE',
    identifierFull: 'Patriots',
    identifierAbbr: 'Pats',
  }),
  new TeamInitData({
    regionFull: 'New Orleans',
    regionAbbr: 'NO',
    identifierFull: 'Saints',
    identifierAbbr: 'Saints',
  }),
  new TeamInitData({
    regionFull: 'New York',
    regionAbbr: 'NYG',
    identifierFull: 'Giants',
    identifierAbbr: 'Giants',
  }),
  new TeamInitData({
    regionFull: 'New York',
    regionAbbr: 'NYJ',
    identifierFull: 'Jets',
    identifierAbbr: 'Jets',
  }),
  new TeamInitData({
    regionFull: 'Philadelphia',
    regionAbbr: 'PHI',
    identifierFull: 'Eagles',
    identifierAbbr: 'Eagles',
  }),
  new TeamInitData({
    regionFull: 'Pittsburgh',
    regionAbbr: 'PIT',
    identifierFull: 'Steelers',
    identifierAbbr: 'Steelers',
  }),
  new TeamInitData({
    regionFull: 'San Francisco',
    regionAbbr: 'SF',
    identifierFull: '49ers',
    identifierAbbr: 'Niners',
  }),
  new TeamInitData({
    regionFull: 'Seattle',
    regionAbbr: 'SEA',
    identifierFull: 'Seahawks',
    identifierAbbr: 'Hawks',
  }),
  new TeamInitData({
    regionFull: 'Tampa Bay',
    regionAbbr: 'TB',
    identifierFull: 'Buccaneers',
    identifierAbbr: 'Bucs',
  }),
  new TeamInitData({
    regionFull: 'Tennessee',
    regionAbbr: 'TEN',
    identifierFull: 'Titans',
    identifierAbbr: 'Titans',
  }),
  new TeamInitData({
    regionFull: 'Washington',
    regionAbbr: 'WAS',
    identifierFull: 'Commanders',
    identifierAbbr: 'Commanders',
  }),
];
