import { ITeamData } from './i-team-data';

export const mlbTeamData: Array<ITeamData> = [
  {
    regionFull: 'Arizona',
    regionAbbr: 'ARI',
    identifierFull: 'Diamondbacks',
    identifierAbbr: 'D-backs',
  },
  {
    regionFull: 'Atlanta',
    regionAbbr: 'ATL',
    identifierFull: 'Braves',
    identifierAbbr: 'Braves',
  },
  {
    regionFull: 'Baltimore',
    regionAbbr: 'BAL',
    identifierFull: 'Orioles',
    identifierAbbr: 'O\'s',
  },
  {
    regionFull: 'Boston',
    regionAbbr: 'BOS',
    identifierFull: 'Red Sox',
    identifierAbbr: 'Sox',
  },
  {
    regionFull: 'Chicago',
    regionAbbr: 'CWS',
    identifierFull: 'White Sox',
    identifierAbbr: 'Sox',
  },
  {
    regionFull: 'Chicago',
    regionAbbr: 'CHC',
    identifierFull: 'Cubs',
    identifierAbbr: 'Cubs',
  },
  {
    regionFull: 'Cincinnati',
    regionAbbr: 'CIN',
    identifierFull: 'Reds',
    identifierAbbr: 'Reds',
  },
  {
    regionFull: 'Cleveland',
    regionAbbr: 'CLE',
    identifierFull: 'Guardians',
    identifierAbbr: 'Guardians',
  },
  {
    regionFull: 'Colorado',
    regionAbbr: 'COL',
    identifierFull: 'Rockies',
    identifierAbbr: 'Rockies',
  },
  {
    regionFull: 'Detroit',
    regionAbbr: 'DET',
    identifierFull: 'Tigers',
    identifierAbbr: 'Tigers',
  },
  {
    regionFull: 'Houston',
    regionAbbr: 'HOU',
    identifierFull: 'Astros',
    identifierAbbr: 'Astros',
  },
  {
    regionFull: 'Kansas City',
    regionAbbr: 'KC',
    identifierFull: 'Royals',
    identifierAbbr: 'Royals',
  },
  {
    regionFull: 'Los Angeles',
    regionAbbr: 'LAA',
    identifierFull: 'Angels',
    identifierAbbr: 'Angels',
  },
  {
    regionFull: 'Los Angeles',
    regionAbbr: 'LAD',
    identifierFull: 'Dodgers',
    identifierAbbr: 'Dodgers',
  },
  {
    regionFull: 'Miami',
    regionAbbr: 'MIA',
    identifierFull: 'Marlins',
    identifierAbbr: 'Marlins',
  },
  {
    regionFull: 'Milwaukee',
    regionAbbr: 'MIL',
    identifierFull: 'Brewers',
    identifierAbbr: 'Brewers',
  },
  {
    regionFull: 'Minnesota',
    regionAbbr: 'MIN',
    identifierFull: 'Twins',
    identifierAbbr: 'Twins',
  },
  {
    regionFull: 'New York',
    regionAbbr: 'NYY',
    identifierFull: 'Yankees',
    identifierAbbr: 'Yanks',
  },
  {
    regionFull: 'New York',
    regionAbbr: 'NYM',
    identifierFull: 'Mets',
    identifierAbbr: 'Mets',
  },
  {
    regionFull: 'Oakland',
    regionAbbr: 'OAK',
    identifierFull: 'Athletics',
    identifierAbbr: 'A\'s',
  },
  {
    regionFull: 'Philadelphia',
    regionAbbr: 'PHI',
    identifierFull: 'Phillies',
    identifierAbbr: 'Phillies',
  },
  {
    regionFull: 'Pittsburgh',
    regionAbbr: 'PIT',
    identifierFull: 'Pirates',
    identifierAbbr: 'Pirates',
  },
  {
    regionFull: 'San Diego',
    regionAbbr: 'SD',
    identifierFull: 'Padres',
    identifierAbbr: 'Padres',
  },
  {
    regionFull: 'San Francisco',
    regionAbbr: 'SF',
    identifierFull: 'Giants',
    identifierAbbr: 'Giants',
  },
  {
    regionFull: 'Seattle',
    regionAbbr: 'SEA',
    identifierFull: 'Mariners',
    identifierAbbr: 'Mariners',
  },
  {
    regionFull: 'Saint Louis',
    regionAbbr: 'STL',
    identifierFull: 'Cardinals',
    identifierAbbr: 'Cards',
  },
  {
    regionFull: 'Tampa Bay',
    regionAbbr: 'TB',
    identifierFull: 'Rays',
    identifierAbbr: 'Rays',
  },
  {
    regionFull: 'Texas',
    regionAbbr: 'TEX',
    identifierFull: 'Rangers',
    identifierAbbr: 'Rangers',
  },
  {
    regionFull: 'Toronto',
    regionAbbr: 'TOR',
    identifierFull: 'Blue Jays',
    identifierAbbr: 'Jays',
  },
  {
    regionFull: 'Washington',
    regionAbbr: 'WSH',
    identifierFull: 'Nationals',
    identifierAbbr: 'Nats',
  },
];