import { TeamInitData } from '.';

export const nbaTeamsInitData: Array<TeamInitData> = [
  new TeamInitData({
    regionFull: 'Atlanta',
    regionAbbr: 'ATL',
    identifierFull: 'Hawks',
    identifierAbbr: 'Hawks',
  }),
  new TeamInitData({
    regionFull: 'Boston',
    regionAbbr: 'BOS',
    identifierFull: 'Celtics',
    identifierAbbr: 'Celtics',
  }),
  new TeamInitData({
    regionFull: 'Brooklyn',
    regionAbbr: 'BKN',
    identifierFull: 'Nets',
    identifierAbbr: 'Nets',
  }),
  new TeamInitData({
    regionFull: 'Charlotte',
    regionAbbr: 'CHA',
    identifierFull: 'Hornets',
    identifierAbbr: 'Hornets',
  }),
  new TeamInitData({
    regionFull: 'Chicago',
    regionAbbr: 'CHI',
    identifierFull: 'Bulls',
    identifierAbbr: 'Bulls',
  }),
  new TeamInitData({
    regionFull: 'Cleveland',
    regionAbbr: 'CLE',
    identifierFull: 'Cavaliers',
    identifierAbbr: 'Cavs',
  }),
  new TeamInitData({
    regionFull: 'Dallas',
    regionAbbr: 'DAL',
    identifierFull: 'Mavericks',
    identifierAbbr: 'Mavs',
  }),
  new TeamInitData({
    regionFull: 'Denver',
    regionAbbr: 'DEN',
    identifierFull: 'Nuggets',
    identifierAbbr: 'Nugs',
  }),
  new TeamInitData({
    regionFull: 'Detroit',
    regionAbbr: 'DET',
    identifierFull: 'Pistons',
    identifierAbbr: 'Pistons',
  }),
  new TeamInitData({
    regionFull: 'Golden State',
    regionAbbr: 'GSW',
    identifierFull: 'Warriors',
    identifierAbbr: 'Dubs',
  }),
  new TeamInitData({
    regionFull: 'Houston',
    regionAbbr: 'HOU',
    identifierFull: 'Rockets',
    identifierAbbr: 'Rockets',
  }),
  new TeamInitData({
    regionFull: 'Indiana',
    regionAbbr: 'IND',
    identifierFull: 'Pacers',
    identifierAbbr: 'Pacers',
  }),
  new TeamInitData({
    regionFull: 'Los Angeles',
    regionAbbr: 'LAC',
    identifierFull: 'Clippers',
    identifierAbbr: 'Clippers',
  }),
  new TeamInitData({
    regionFull: 'Los Angeles',
    regionAbbr: 'LAL',
    identifierFull: 'Lakers',
    identifierAbbr: 'Lakers',
  }),
  new TeamInitData({
    regionFull: 'Memphis',
    regionAbbr: 'MEM',
    identifierFull: 'Grizzlies',
    identifierAbbr: 'Grizz',
  }),
  new TeamInitData({
    regionFull: 'Miami',
    regionAbbr: 'MIA',
    identifierFull: 'Heat',
    identifierAbbr: 'Heat',
  }),
  new TeamInitData({
    regionFull: 'Milwaukee',
    regionAbbr: 'MIL',
    identifierFull: 'Bucks',
    identifierAbbr: 'Bucks',
  }),
  new TeamInitData({
    regionFull: 'Minnesota',
    regionAbbr: 'MIN',
    identifierFull: 'Timberwolves',
    identifierAbbr: 'Wolves',
  }),
  new TeamInitData({
    regionFull: 'New Orleans',
    regionAbbr: 'NOP',
    identifierFull: 'Pelicans',
    identifierAbbr: 'Pels',
  }),
  new TeamInitData({
    regionFull: 'New York',
    regionAbbr: 'NYK',
    identifierFull: 'Knicks',
    identifierAbbr: 'Knicks',
  }),
  new TeamInitData({
    regionFull: 'Oklahoma City',
    regionAbbr: 'OKC',
    identifierFull: 'Thunder',
    identifierAbbr: 'Thunder',
  }),
  new TeamInitData({
    regionFull: 'Orlando',
    regionAbbr: 'ORL',
    identifierFull: 'Magic',
    identifierAbbr: 'Magic',
  }),
  new TeamInitData({
    regionFull: 'Philadelphia',
    regionAbbr: 'PHI',
    identifierFull: '76ers',
    identifierAbbr: 'Sixers',
  }),
  new TeamInitData({
    regionFull: 'Phoenix',
    regionAbbr: 'PHX',
    identifierFull: 'Suns',
    identifierAbbr: 'Suns',
  }),
  new TeamInitData({
    regionFull: 'Portland',
    regionAbbr: 'POR',
    identifierFull: 'Trail Blazers',
    identifierAbbr: 'Blazers',
  }),
  new TeamInitData({
    regionFull: 'Sacramento',
    regionAbbr: 'SAC',
    identifierFull: 'Kings',
    identifierAbbr: 'Kings',
  }),
  new TeamInitData({
    regionFull: 'San Antonio',
    regionAbbr: 'SAS',
    identifierFull: 'Spurs',
    identifierAbbr: 'Spurs',
  }),
  new TeamInitData({
    regionFull: 'Toronto',
    regionAbbr: 'TOR',
    identifierFull: 'Raptors',
    identifierAbbr: 'Raptors',
  }),
  new TeamInitData({
    regionFull: 'Utah',
    regionAbbr: 'UTA',
    identifierFull: 'Jazz',
    identifierAbbr: 'Jazz',
  }),
  new TeamInitData({
    regionFull: 'Washington',
    regionAbbr: 'WAS',
    identifierFull: 'Wizards',
    identifierAbbr: 'Wizards',
  }),
];
