export const nbaTeams = [
    {
        regionFull: 'Atlanta',
        regionAbbr: 'ATL',
        identifierFull: 'Hawks',
        identifierAbbr: 'Hawks',
    },
    {
        regionFull: 'Boston',
        regionAbbr: 'BOS',
        identifierFull: 'Celtics',
        identifierAbbr: 'Celtics',
    },
    {
        regionFull: 'Brooklyn',
        regionAbbr: 'BKN',
        identifierFull: 'Nets',
        identifierAbbr: 'Nets',
    },
    {
        regionFull: 'Charlotte',
        regionAbbr: 'CHA',
        identifierFull: 'Hornets',
        identifierAbbr: 'Hornets',
    },
    {
        regionFull: 'Chicago',
        regionAbbr: 'CHI',
        identifierFull: 'Bulls',
        identifierAbbr: 'Bulls',
    },
    {
        regionFull: 'Cleveland',
        regionAbbr: 'CLE',
        identifierFull: 'Cavaliers',
        identifierAbbr: 'Cavs',
    },
    {
        regionFull: 'Dallas',
        regionAbbr: 'DAL',
        identifierFull: 'Mavericks',
        identifierAbbr: 'Mavs',
    },
    {
        regionFull: 'Denver',
        regionAbbr: 'DEN',
        identifierFull: 'Nuggets',
        identifierAbbr: 'Nugs',
    },
    {
        regionFull: 'Detroit',
        regionAbbr: 'DET',
        identifierFull: 'Pistons',
        identifierAbbr: 'Pistons',
    },
    {
        regionFull: 'Golden State',
        regionAbbr: 'GSW',
        identifierFull: 'Warriors',
        identifierAbbr: 'Warriors',
    },
    {
        regionFull: 'Houston',
        regionAbbr: 'HOU',
        identifierFull: 'Rockets',
        identifierAbbr: 'Rockets',
    },
    {
        regionFull: 'Indiana',
        regionAbbr: 'IND',
        identifierFull: 'Pacers',
        identifierAbbr: 'Pacers',
    },
    {
        regionFull: 'Los Angeles',
        regionAbbr: 'LAC',
        identifierFull: 'Clippers',
        identifierAbbr: 'Clippers',
    },
    {
        regionFull: 'Los Angeles',
        regionAbbr: 'LAL',
        identifierFull: 'Lakers',
        identifierAbbr: 'Lakers',
    },
    {
        regionFull: 'Memphis',
        regionAbbr: 'MEM',
        identifierFull: 'Grizzlies',
        identifierAbbr: 'Grizzlies',
    },
    {
        regionFull: 'Miami',
        regionAbbr: 'MIA',
        identifierFull: 'Heat',
        identifierAbbr: 'Heat',
    },
    {
        regionFull: 'Milwaukee',
        regionAbbr: 'MIL',
        identifierFull: 'Bucks',
        identifierAbbr: 'Bucks',
    },
    {
        regionFull: 'Minnesota',
        regionAbbr: 'MIN',
        identifierFull: 'Timberwolves',
        identifierAbbr: 'Wolves',
    },
    {
        regionFull: 'New Orleans',
        regionAbbr: 'NOP',
        identifierFull: 'Pelicans',
        identifierAbbr: 'Pels',
    },
    {
        regionFull: 'New York',
        regionAbbr: 'NYK',
        identifierFull: 'Knicks',
        identifierAbbr: 'Knicks',
    },
    {
        regionFull: 'Oklahoma City',
        regionAbbr: 'OKC',
        identifierFull: 'Thunder',
        identifierAbbr: 'Thunder',
    },
    {
        regionFull: 'Orlando',
        regionAbbr: 'ORL',
        identifierFull: 'Magic',
        identifierAbbr: 'Magic',
    },
    {
        regionFull: 'Philadelphia',
        regionAbbr: 'PHI',
        identifierFull: '76ers',
        identifierAbbr: 'Sixers',
    },
    {
        regionFull: 'Phoenix',
        regionAbbr: 'PHX',
        identifierFull: 'Suns',
        identifierAbbr: 'Suns',
    },
    {
        regionFull: 'Portland',
        regionAbbr: 'POR',
        identifierFull: 'Trail Blazers',
        identifierAbbr: 'Blazers',
    },
    {
        regionFull: 'Sacramento',
        regionAbbr: 'SAC',
        identifierFull: 'Kings',
        identifierAbbr: 'Kings',
    },
    {
        regionFull: 'San Antonio',
        regionAbbr: 'SAS',
        identifierFull: 'Spurs',
        identifierAbbr: 'Spurs',
    },
    {
        regionFull: 'Toronto',
        regionAbbr: 'TOR',
        identifierFull: 'Raptors',
        identifierAbbr: 'Raptors',
    },
    {
        regionFull: 'Utah',
        regionAbbr: 'UTA',
        identifierFull: 'Jazz',
        identifierAbbr: 'Jazz',
    },
    {
        regionFull: 'Washington',
        regionAbbr: 'WAS',
        identifierFull: 'Wizards',
        identifierAbbr: 'Wizards',
    },
];