import { TeamDatum } from './team-datum';

export const nflTeamData: Array<TeamDatum> = [
  {
    key: 'arizonaCardinals',
    regionFull: 'Arizona',
    regionAbbr: 'ARI',
    nameFull: 'Cardinals',
    nameAbbr: 'Cards',
  },
  {
    key: 'atlantaFalcons',
    regionFull: 'Atlanta',
    regionAbbr: 'ATL',
    nameFull: 'Falcons',
    nameAbbr: 'Falcs',
  },
  {
    key: 'baltimoreRavens',
    regionFull: 'Baltimore',
    regionAbbr: 'BAL',
    nameFull: 'Ravens',
    nameAbbr: 'Raves',
  },
  {
    key: 'buffaloBills',
    regionFull: 'Buffalo',
    regionAbbr: 'BUF',
    nameFull: 'Bills',
    nameAbbr: 'Bills',
  },
  {
    key: 'carolinaPanthers',
    regionFull: 'Carolina',
    regionAbbr: 'CAR',
    nameFull: 'Panthers',
    nameAbbr: 'Panthers',
  },
  {
    key: 'chicagoBears',
    regionFull: 'Chicago',
    regionAbbr: 'CHI',
    nameFull: 'Bears',
    nameAbbr: 'Bears',
  },
  {
    key: 'cincinnatiBengals',
    regionFull: 'Cincinnati',
    regionAbbr: 'CIN',
    nameFull: 'Bengals',
    nameAbbr: 'Bengals',
  },
  {
    key: 'clevelandBrowns',
    regionFull: 'Cleveland',
    regionAbbr: 'CLE',
    nameFull: 'Browns',
    nameAbbr: 'Browns',
  },
  {
    key: 'dallasCowboys',
    regionFull: 'Dallas',
    regionAbbr: 'DAL',
    nameFull: 'Cowboys',
    nameAbbr: 'Cowboys',
  },
  {
    key: 'denverBroncos',
    regionFull: 'Denver',
    regionAbbr: 'DEN',
    nameFull: 'Broncos',
    nameAbbr: 'Broncs',
  },
  {
    key: 'detroitLions',
    regionFull: 'Detroit',
    regionAbbr: 'DET',
    nameFull: 'Lions',
    nameAbbr: 'Lions',
  },
  {
    key: 'greenBayPackers',
    regionFull: 'Green Bay',
    regionAbbr: 'GB',
    nameFull: 'Packers',
    nameAbbr: 'Packers',
  },
  {
    key: 'houstonTexans',
    regionFull: 'Houston',
    regionAbbr: 'HOU',
    nameFull: 'Texans',
    nameAbbr: 'Texans',
  },
  {
    key: 'indianapolisColts',
    regionFull: 'Indianapolis',
    regionAbbr: 'IND',
    nameFull: 'Colts',
    nameAbbr: 'Colts',
  },
  {
    key: 'jacksonvilleJaguars',
    regionFull: 'Jacksonville',
    regionAbbr: 'JAX',
    nameFull: 'Jaguars',
    nameAbbr: 'Jags',
  },
  {
    key: 'kansasCityChiefs',
    regionFull: 'Kansas City',
    regionAbbr: 'KC',
    nameFull: 'Chiefs',
    nameAbbr: 'Chiefs',
  },
  {
    key: 'lasVegasRaiders',
    regionFull: 'Las Vegas',
    regionAbbr: 'LV',
    nameFull: 'Raiders',
    nameAbbr: 'Raiders',
  },
  {
    key: 'losAngelesChargers',
    regionFull: 'Los Angeles',
    regionAbbr: 'LAC',
    nameFull: 'Chargers',
    nameAbbr: 'Chargers',
  },
  {
    key: 'losAngelesRams',
    regionFull: 'Los Angeles',
    regionAbbr: 'LAR',
    nameFull: 'Rams',
    nameAbbr: 'Rams',
  },
  {
    key: 'miamiDolphins',
    regionFull: 'Miami',
    regionAbbr: 'MIA',
    nameFull: 'Dolphins',
    nameAbbr: 'Fins',
  },
  {
    key: 'minnesotaVikings',
    regionFull: 'Minnesota',
    regionAbbr: 'MIN',
    nameFull: 'Vikings',
    nameAbbr: 'Vikes',
  },
  {
    key: 'newEnglandPatriots',
    regionFull: 'New England',
    regionAbbr: 'NE',
    nameFull: 'Patriots',
    nameAbbr: 'Pats',
  },
  {
    key: 'newOrleansSaints',
    regionFull: 'New Orleans',
    regionAbbr: 'NO',
    nameFull: 'Saints',
    nameAbbr: 'Saints',
  },
  {
    key: 'newYorkGiants',
    regionFull: 'New York',
    regionAbbr: 'NYG',
    nameFull: 'Giants',
    nameAbbr: 'Giants',
  },
  {
    key: 'newYorkJets',
    regionFull: 'New York',
    regionAbbr: 'NYJ',
    nameFull: 'Jets',
    nameAbbr: 'Jets',
  },
  {
    key: 'philadelphiaEagles',
    regionFull: 'Philadelphia',
    regionAbbr: 'PHI',
    nameFull: 'Eagles',
    nameAbbr: 'Eagles',
  },
  {
    key: 'pittsburghSteelers',
    regionFull: 'Pittsburgh',
    regionAbbr: 'PIT',
    nameFull: 'Steelers',
    nameAbbr: 'Steelers',
  },
  {
    key: 'sanFrancisco49ers',
    regionFull: 'San Francisco',
    regionAbbr: 'SF',
    nameFull: '49ers',
    nameAbbr: 'Niners',
  },
  {
    key: 'seattleSeahawks',
    regionFull: 'Seattle',
    regionAbbr: 'SEA',
    nameFull: 'Seahawks',
    nameAbbr: 'Seahawks',
  },
  {
    key: 'tampaBayBuccaneers',
    regionFull: 'Tampa Bay',
    regionAbbr: 'TB',
    nameFull: 'Buccaneers',
    nameAbbr: 'Bucs',
  },
  {
    key: 'tennesseeTitans',
    regionFull: 'Tennessee',
    regionAbbr: 'TEN',
    nameFull: 'Titans',
    nameAbbr: 'Titans',
  },
  {
    key: 'washingtonFootballTeam',
    regionFull: 'Washington',
    regionAbbr: 'WAS',
    nameFull: 'Football Team',
    nameAbbr: 'WFT',
  },
];
